### ISSUE TITLE
reduce visual impact

### ISSUE THREAD

**Issue by FDIM** [remithomas/eslint-plugin-ban#14]
I'm in the process of migrating to eslint from tslint, and this minor thing would be nice to take care of.

In the project we are banning calls to fit and fdescribe to prevent green build, this extension does this wonderfully.

Now the irk for me is this in vscode editor:
![image](https://user-images.githubusercontent.com/1985429/102356908-1ab71e80-3fae-11eb-9945-fd3c3b0feaba.png)

tslint was simply highlighting the function name instead of entire block:
![image](https://user-images.githubusercontent.com/1985429/102357029-33273900-3fae-11eb-89aa-0549add1a6ba.png)

Meaning you could still work normally, without seeing half/entire file being red. I can probably submit a PR if you are interested? Should be a small change to return different indexes ?

**Comment by remithomas** [comment]
Hello @FDIM, thanks for the report. Indeed this could be better, of course I'm interested, feel to create a MR 😄 
thanks a lot
