### ISSUE TITLE
Smaller range for the reported error

### ISSUE THREAD

**Issue by felixfbecker** [remithomas/eslint-plugin-ban#4]
With TSLint's ban rule configured to ban `it.only()`, this code would report a warning for the `only` part:
```ts
it.only('does abc', () => {
   ^^^^
  const foo = callFn()
  assert.equal(foo, 'bar')
})
```

This was nice because it is unobtrusive when debugging a test but makes sure you don't accidentally commit & merge the `only` into master.

The ESLint plugin unfortunately reports an error for the entire function call:

```ts
it.only('does abc', () => {
   ^^^^^^^^^^^^^^^^^^^^^^^^
  const foo = callFn()
^^^^^^^^^^^^^^^^^^^^^^
  assert.equal(foo, 'bar')
^^^^^^^^^^^^^^^^^^^^^^^^^^
})
^
```

This makes writing code with all the distraction difficult, which results in people adding `eslint-disable` while debugging, which means the protection from merging it into master is gone :/

Could this range be reduced to only include the identifier, like TSLint?

**Comment by remithomas** [comment]
yes, indeed. Thanks for the report. I will work on it.

**Comment by remithomas** [comment]
This should be fixed with this last version, just published.
